name: Build installer for supported os
on: push

env:
    ic_ci: true

jobs:
    build-app:
        strategy:
            matrix:
                os: [ macos-latest,ubuntu-20.04,windows-latest ]
        name: Build the application
        runs-on: ${{ matrix.os }}
        continue-on-error: true
        steps:
            - name: Make gradlew executable
              run: chmod +x gradlew
            - name: checkout
              uses: actions/checkout@v2
            - name: Setup Java
              uses: actions/setup-java@v1
              with:
                  java-version: 18
            - run: ./gradlew jpackage
            - run: mkdir staging && cp build/jpackage/* staging
            - name: upload build result
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: staging
                  asset_name: Electronic-Shop-JavaFX-${{matrix.os}}
                  asset_content_type: application/zip
#                  path: staging
