name: Build installer

on:
    push:
        branches:
            - 'master'

permissions:
    contents: write

jobs:
    build-app:
        strategy:
            matrix:
                os: [ windows-latest ]
        name: Build the application
        runs-on: ${{ matrix.os }}
        continue-on-error: true
        steps:
            -   name: checkout
                uses: actions/checkout@v2
            -   name: Setup Java
                uses: actions/setup-java@v1
                with:
                    java-version: 18
            -   run: ./gradlew jpackage
            -   run: mkdir staging && cp build/jpackage/* staging
            -   name: Release
                uses: softprops/action-gh-release@v1
                env:
                    GITHUB_TOKEN: ${{ github.token }}
                with:
                    tag_name: github.ref
                    prerelease: true
                    files: staging
