name: Build installer for supported os
on: push

jobs:
    build-app:
        strategy:
            matrix:
                os: [ macos-latest,ubuntu-20.04,windows-latest ]
        name: Build the application
        runs-on: ${{ matrix.os }}
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: Setup Java
              uses: actions/setup-java@v1
              with:
                  java-version: 18
            - run: ./gradlew jpackage
            - continue-on-error: true
            - run: mkdir staging && cp build/jpackage/* staging
            - name: upload build result
              uses: actions/upload-artifact@v2
              with:
                  name: Electronic-Shop-JavaFX-${{matrix.os}}
                  path: staging
