name: Build installer

on:
    push:
        branches:
            - 'master'

permissions:
    contents: write

jobs:
    build-app:
        strategy:
            matrix:
                os: [ windows-latest ]
        name: Build the application
        runs-on: ${{ matrix.os }}
        continue-on-error: true
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Injecting version
                id: version
                run: echo "::set-output name=version::$(cat .version)"
            -   name: Setup JDK
                uses: actions/setup-java@v1
                with:
                    java-version: 18
            -   name: Packaging bundle
                run: ./gradlew jpackage
            -   name: Zipping bundle
                uses: papeloto/action-zip@v1
                with:
                    files: app/build/jpackage/app
                    dest: app/build/jpackage/app-dist.zip
            -   name: Preparing bundle
                run: mkdir staging && cp app/build/jpackage/* staging
            -   name: Release
                uses: softprops/action-gh-release@v1
                env:
                    GITHUB_TOKEN: ${{ github.token }}
                with:
                    tag_name: ${{ steps.version.outputs.version }}
                    prerelease: true
                    files: |
                        staging/**.msi
                        staging/**.zip
            -   name: Updating version number
                uses: EndBug/add-and-commit@v9
                with:
                    default_author: github_actions
                    add: '.version'
                    message: Version updated
